apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-app
spec:
  selector:
    matchLabels:
      app: hello-app
  replicas: 3
  template:
    metadata:
      labels:
        app: hello-app
    spec:
      containers:
      - name: hello
        image: "us-docker.pkg.dev/google-samples/containers/gke/hello-app:1.0"
---
apiVersion: v1
kind: Service
metadata:
  name: hello-app-lb
spec:
  type: LoadBalancer
  selector:
    app: hello-app
  loadBalancerClass: k-ngrok.io/default
  allocateLoadBalancerNodePorts: false
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
    name: app
